# Generated by Django 4.0 on 2021-12-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_city_profile_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
