# Generated by Django 4.0 on 2021-12-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_image_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='D:\tadaawy.jpg', null=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
