# Generated by Django 4.0 on 2021-12-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_diseases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
