# Generated by Django 4.0 on 2021-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_remove_diseases_id_alter_diseases_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
