# Generated by Django 4.0 on 2021-12-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_diseases_id_alter_diseases_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
