# Generated by Django 4.0 on 2021-12-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_alter_diseases_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='id',
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
