# Generated by Django 4.0 on 2021-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='D:\tadaawy.jpg', null=True, upload_to='photo/%y/%m/%d')),
                ('name', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=600)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
