# Generated by Django 4.0 on 2021-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicines_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
